# Autoformatter friendly markdownlint config (all formatting rules disabled)
default: true
# blank_lines: false
# bullet: false
# html: false
# indentation: false
line_length: false
# spaces: false
# url: false
# whitespace: false

MD007:
    # Spaces for indent
    indent: 2
    # Whether to indent the first level of the list
    start_indented: true
    # Spaces for first level indent (when start_indented is set)
    start_indent: 2

MD032: false

MD012:
    # Consecutive blank lines
    maximum: 2

MD033: false
